# Generated by Django 3.2.6 on 2021-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
